#!/bin/bash

python_cmd='python3'
# Fallback to Python 2, if Python 3 is not available
command -v python3 > /dev/null || python_cmd='python'

BASEDIR=$(dirname $0)

if [ $(id -u) = "0" ]; then
    $python_cmd -u $BASEDIR/../python/visionunet.py $@
else
    sudo $python_cmd -u $BASEDIR/../python/visionunet.py $@
fi
